spring:
  main:
    banner-mode: off

# describes target for load testing
application-target:
  # comma-separated target instances host:port
  urls: http://localhost:8080,
        http://127.0.0.1:8081
  # comma-separated REST API endpoints in one target
  endpoints: /app1/v1/target-endpoint1, 
             /app1/v1/target-endpoint2

loader-config:
  # testing period in seconds for each endpoint
  testing-period-seconds: 5
  # number of requests which would be made during testing period for each endpoint
  requests-per-second: 10
  # load testing profile - local (on local machine) / remote (on remote host)
  profile: LOCAL
  # process-per-instance (on jvm for each target instance)
  process-per-instance: true





