version: '3'

services:
  prometheus:
    build:
      context: ./prometheus
    ports:
      - "9090:9090"
    #volumes:
    #  - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

  grafana:
    build:
      context: ./grafana
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
